[package]
name = "redumb"
version = "0.3.0"
edition = "2024"

[lib]
name      = "redumb"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
regex = "1.8"
base64 = "0.21"
indexmap = "1.9"
thiserror = "1.0"
indicatif = "0.17"
